version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf